const events = [
  {
    image: "/images/Events/Event-1.webp",
    date: "11 March 2025",
    title: "The way of the Wolf",
    description: "Mastering Game Design and Storytelling",
    Mode: "Online",
    venue: "NIT RKL",
    link: "https://www.gametoaim.live/",
  },
  {
    image: "/images/Events/Event-2.jpeg",
    date: "15 December 2024",
    title: "3D Modelling",
    description: "Introduction to 3D modelling in Blender",
    Mode: "Online",
    venue: "NIT RKL",
    link: "https://www.instagram.com/p/C01a-IlP1Sy/?utm_source=ig_web_copy_link",
  },
  {
    image: "/images/Events/Event-3.jpeg",
    date: "18 December 2025 - 28 December 2025",
    title: "Game Development Workshop",
    description: "Exploring the basics of game development",
    Mode: "Online",
    venue: "NIT RKL",
    link: "https://www.instagram.com/p/DSSmgkOifrK/?utm_source=ig_web_copy_link",
  },
  {
    image: "/images/Events/Event-4.jpeg",
    date: "8 November 2025",
    title: "Reef Rumble",
    description: "Experience virtual reality",
    Mode: "Offline",
    venue: "NIT RKL",
    link: "https://www.instagram.com/p/DQWzc6wCqh6/?utm_source=ig_web_copy_link",
  },
  {
    image: "/images/Events/Event-5.jpeg",
    date: "31 Jan 2026 - 2 Feb 2026",
    title: "GTA MegaJam",
    description: "Mastering Game Design and Storytelling",
    Mode: "Offline",
    venue: "NIT RKL",
    link: "https://www.instagram.com/game.to.aim/p/DTcUqnPCbdC/",
  },
  {
    image: "/images/Events/Event-6.jpeg",
    date: "11 March 2025",
    title: "The way of the Wolf",
    description: "Mastering Game Design and Storytelling",
    Mode: "Online",
    venue: "NIT RKL",
    link: "https://www.instagram.com/p/DJcPblWyrev/?utm_source=ig_web_copy_link",
  },
];

export default events;
